# -*- coding: utf-8 -*-
"""DeepByWriterVisAcc_Sigmoid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZ63y8tcKWBnVSsvphhgGKcw37DF4sH8
"""



import sys
sys.version
!pip install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

!pip install -U pillow
import PIL
print(PIL.PILLOW_VERSION)
#!pip uninstall Pillow

!pip3 install torchvision

!{sys.executable} -m pip install torchtext==0.2.3
#pip install torchtext==0.2.3

pip install hiddenlayer

# %matplotlib inline
import torchvision
import torchvision.datasets as dset
from torchvision.datasets import ImageFolder
import torchvision.transforms as transforms
from torch.utils.data import DataLoader,Dataset
import matplotlib.pyplot as plt
import torchvision.utils
import numpy as np
import hiddenlayer as hl
import random
from PIL import Image
import torch
from torch.autograd import Variable
import PIL.ImageOps    
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from google.colab import drive
drive.mount('/content/drive')


#torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True) CONV2D
#torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False) MAX POOLING
class SiameseNetwork(nn.Module):
  def __init__(self):
    super(SiameseNetwork, self).__init__()
    self.conv1 = nn.Sequential(
      nn.Conv2d(1,4,kernel_size=3),
      nn.ReLU(),
      nn.BatchNorm2d(4),
      nn.MaxPool2d(2,2),
      )
    self.conv2 = nn.Sequential(
      nn.Conv2d(4,8,kernel_size=3),
      nn.ReLU(),
      nn.BatchNorm2d(8),
      nn.MaxPool2d(2,2),
      )
    
    self.conv3 = nn.Sequential(
      nn.Conv2d(8,8,kernel_size=3),
      nn.ReLU(),
      nn.BatchNorm2d(8),
      nn.MaxPool2d(2,2),
      )
    self.fully_c1 =nn.Sequential(
      nn.Linear(8*10*10,1024),
      nn.ReLU(),
      )
      
    self.fully_c2 =nn.Sequential(
      nn.Linear(2048,1),
      nn.Sigmoid(),
      )
    
  def forward(self,input1,input2):
    input1=self.conv1(input1)
    #print(input1.size())
    input1=self.conv2(input1)
    #print(input1.size())
    input1=self.conv3(input1) 
    input1=input1.view(-1,C*H*W)
    input1= self.fully_c1(input1)
    
    
    input2=self.conv1(input2)
    input2=self.conv2(input2)
    input2=self.conv3(input2)
    input2= self.fully_c1(input2)
    
    output_my=torch.cat((input1,input2),1)
    output_my= self.fully_c2(output_my)
    return output_my

class SiameseNetworkDataset(Dataset):
  def __init__(self,imageFolderDataset,transform=None,should_invert=True):
    self.imageFolderDataset = imageFolderDataset
    self.should_invert = should_invert
    self.transform=transform
  
  def __getitem__(self,index):
    img0_tuple = random.choice(self.imageFolderDataset.imgs)
    
    #randomise getting one class.
    should_get_same_class = random.randint(0,1)
    
    if should_get_same_class:
      while True:
        img1_tuple =random.choice(self.imageFolderDataset.imgs)
        if img0_tuple[1] == img1_tuple[1]:
          break
    else:
      img1_tuple =random.choice(self.imageFolderDataset.imgs)
    
    img0 =Image.open(img0_tuple[0])
    img1 =Image.open(img1_tuple[0])
    
    img0 = img0.convert("L")
    img1 = img1.convert("L")
    
    if self.should_invert:
      img0 =PIL.ImageOps.invert(img0)
      img1 =PIL.ImageOps.invert(img1)
    if self.transform is not None:
      img0 = self.transform(img0)
      img1 = self.transform(img1)
      
    return img0, img1,torch.from_numpy(np.array([int(img1_tuple[1]!=img0_tuple[1])],dtype=np.float32))
  
  def __len__(self):
    return len(self.imageFolderDataset.imgs)

!ls "/content/drive/My Drive/ColabNotebooks/data/testing_1"
print("PyTorch version: ")
print(torch.__version__)
print("CUDA Version: ")
print(torch.version.cuda)
print("cuDNN version is: ")
print(torch.backends.cudnn.version())

def imshow(img,text=None,should_save=False):
  npimg = img.numpy()
  plt.axis("off")
  if text:
    plt.text(75, 8,text,style='italic',fontweight='bold',bbox={'facecolor':'white','alpha':0.8,'pad':10})
  plt.imshow(np.transpose(npimg,(1,2,0)))
  plt.show()
def show_plot(iteration,loss,labelx,labely):
  plt.xlabel(labelx)
  plt.ylabel(labely)
  plt.plot(iteration,loss)
  plt.show()

folder_dataset = dset.ImageFolder(root="/content/drive/My Drive/ColabNotebooks/DataProcessed/final_data/training_0/")
siamese_dataset = SiameseNetworkDataset(imageFolderDataset=folder_dataset,transform=transforms.Compose([transforms.Resize((100,100)),transforms.ToTensor()]),should_invert=False)

vis_dataloader = DataLoader(siamese_dataset,shuffle=True,num_workers=2,batch_size=2)
dataiter = iter(vis_dataloader)

example_batch=next(dataiter)
concatenated=torch.cat((example_batch[0],example_batch[1]),0)
imshow(torchvision.utils.make_grid(concatenated))
print(example_batch[2].numpy)

train_dataloader = DataLoader(siamese_dataset,shuffle=True,num_workers =4,batch_size=100)

net = SiameseNetwork().cuda()

criterion = nn.BCELoss()

optimizer = optim.Adam(net.parameters(),lr=0.0005)

counter = []

loss_history = []

iteration_number=0

for epoch in range(0,20):
  print("Epoch :",epoch+1,"Training ...")
  for i, data in enumerate(train_dataloader,0):
    img0,img1,label = data
    img0,img1,label=img0.cuda(),img1.cuda(),label.cuda()
    img0,img1,label = Variable(img0),Variable(img1),Variable(label)
    optimizer.zero_grad()
    output =net(img0,img1)
    loss_BCELoss= criterion(output,label)
    if i%100 ==0:
      #print("Epoch number {}\n Current loss {} \n".format(epoch,loss_contrastive.item()))
      print("Epoch number {}\n Current loss {}\n".format(epoch,loss_BCELoss.item()))
      iteration_number +=100
      counter.append(iteration_number)
      #loss_history.append(loss_contrastive.item())
      loss_history.append(loss_BCELoss.item())
    loss_BCELoss.backward()
    optimizer.step()
    
show_plot(counter,loss_history,"Steps","Loss")
torch.save(net,'/content/drive/My Drive/ColabNotebooks/'+"modelBCE.pth")

folder_dataset_test = dset.ImageFolder(root="/content/drive/My Drive/ColabNotebooks/DataProcessed/final_data/testing_0/")
siamese_dataset=SiameseNetworkDataset(imageFolderDataset=folder_dataset_test,transform=transforms.Compose([transforms.Resize((100,100)),transforms.ToTensor()]),should_invert=False)
test_dataloader = DataLoader(siamese_dataset,num_workers=6,batch_size=1,shuffle=False)

correct = 0
total =0
counter1 = []
trace = 0;
accuracy_history = []
net.load_state_dict(torch.load('/content/drive/My Drive/ColabNotebooks/'+"modelBCE.pth"))

for i ,data in enumerate(test_dataloader,0):
  x0,x1,label2=data
  output=net(Variable(x0).cuda(),Variable(x1).cuda())
  label2 = label2.cuda()
  label2 = Variable(label2.float())
  output = output.cpu()
  for j in range(output.size()[0]):
    if(output.data.numpy()[j]<0.5):
      if(label2.data.cpu().numpy()[j]==0):
        correct+=1
        total+=1
      else:
        total+=1
    else:
      if(label2.data.cpu().numpy()[j]==1):
        correct+=1
        total+=1
      else:
        total+=1
  #imshow(torchvision.utils.make_grid(concatenated),'Dissimilarity: {:.2f}'.format(distance.item()))
  print("Accuracy of the network on test images is : %d %%" %(100*correct/total))
  accuracy_history.append(100*correct/total)
  counter1.append(total)
  #print("MY {}".format(label1))
  #image_path = path_name.format(label2)+"/out_"+str(i)+".png"
  #torchvision.utils.save_image(x0,'/content/drive/My Drive/out.png')
  #torchvision.utils.save_image(x0,image_path)
  #imshow(torchvision.utils.make_grid(concatenated),'Dissimilarity: {:.2f}'.format(distance.item()))
show_plot(counter1,accuracy_history," Epoch "," Accuracy ")

